<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'FontBundle\service\MessageGenerator' shared autowired service.

include_once $this->targetDirs[3].'/src/FontBundle/service/MessageGenerator.php';

return $this->services['FontBundle\service\MessageGenerator'] = new \FontBundle\service\MessageGenerator();
