user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

font:
    resource: "@FontBundle/Resources/config/routing.yml"
    prefix:   /

back:
    resource: "@BackBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
fos_user:
    resource: "@UserBundle/Resources/config/routing/all.xml"

