eventtype_index:
    path:     /
    defaults: { _controller: "AppBundle:EventType:index" }
    methods:  GET

eventtype_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:EventType:show" }
    methods:  GET

eventtype_new:
    path:     /new
    defaults: { _controller: "AppBundle:EventType:new" }
    methods:  [GET, POST]

eventtype_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:EventType:edit" }
    methods:  [GET, POST]

eventtype_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:EventType:delete" }
    methods:  DELETE
