<?php

namespace BackBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    
//    public function findTicketCategory($category)
//    {
//        $qb=$this->createQueryBuilder('c');
//        $qb->select('c,t')
//            ->where('c.tickets like :category')
//            ->setParameter('category',$category)
//            ->leftJoin('c.tickets','t')
//            ;
////    return $qb->getQuery()->getResult();
//   return $qb->getQuery()->getDQL();
//    }
}
