<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'user.redirect_after_registration_subscriber' shared autowired service.

include_once $this->targetDirs[3].'/src/UserBundle/EventListener/RedirectAfterRegistrationSubscriber.php';

return $this->services['user.redirect_after_registration_subscriber'] = new \UserBundle\EventListener\RedirectAfterRegistrationSubscriber(${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});
