<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDv4pg7i\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDv4pg7i/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDv4pg7i.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDv4pg7i\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerDv4pg7i\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Dv4pg7i',
    'container.build_id' => 'baa55bb6',
    'container.build_time' => 1542629175,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDv4pg7i');
